### ISSUE TITLE
Labor-Support for 3370, 3390 and others.

### ISSUE THREAD

**Issue by Himan2001** [Freetz/freetz#1]
It is possible to integrate the latest "compile-testing" Labor-Support for the 3370/3390 and other models right now ? - It can be very helpful to fix bugs with the latest versions for this models right now before a final version comes out. The VDSL2-Vectoring Support for this models is much better as from the old 6.30er Final Versions.

**Comment by olistudent** [comment]
Hi. We accept patches otherwise you will have to wait until a developer adds support. As there are many labor versions available at the moment and they do change very often it takes much time to support them all...

**Comment by er13** [comment]
We have no plans to support labor firmwares for boxes other than the flagship ones (as of now 7490, 7590, 7580).
