### ISSUE TITLE
Build schägt fehl beim Packet Download

### ISSUE THREAD

**Issue by Coolzero82** [Freetz/freetz#113]
Hi,
der Build bricht ab beim Versuch die folgenden Pakete zu Downloaden
`Download failed - "http://freetz.magenbrot.net/pcsc-lite-1.8.12.tar.bz2"  ->  error code 8
make: *** [make/pcsc-lite/pcsc-lite.mk:29: dl/pcsc-lite-1.8.12.tar.bz2] Fehler 1
`
`Download failed - "http://freetz.3dfxatwork.de/ccid-1.4.18.tar.bz2"  ->  error code 8
make: *** [make/ccid/ccid.mk:21: dl/ccid-1.4.18.tar.bz2] Fehler 1
`
Sind auf keinem der Server vorhanden,.

Der manuelle Download von z.b. hier
https://pcsclite.apdu.fr/files/
https://src.fedoraproject.org/lookaside/extras/pcsc-lite-ccid/ccid-1.4.18.tar.bz2/8d57342bda53aaee706ef2d02409c4f4/

**Comment by olistudent** [comment]
Paket auf Mirror geladen.
