### ISSUE TITLE
DL-Toolchains für Kernel 3+4

### ISSUE THREAD

**Issue by fda77** [Freetz/freetz#127]
Bei erstellten DL-Toolchains für Kernel 3+4 fehlen leider ein paar Headerdateien, wodurch sich manche Packages nicht bauen lassen.

**Comment by olistudent** [comment]
Geht's auch ein bißchen genauer? Manche und einige ist doch sehr vage...

**Comment by fda77** [comment]
Welche alle fehlen und welche packages betroffen sind weiss ich nicht. Es sind aber zumindest packges die scsi.h brauchen, wie smarttools (siehe email)

**Comment by fda77** [comment]
sg3_utils und hd-idle sind auch betroffen. Hatte übrigens mit aktuellen Xubuntu als auch Fedora mit gleichem Ergebnis gebaut.
Die neueren Toolchains sind in freetz-ng nur als REAL-DEVELOPER auswählbar, falls es sich jemand anschauen möchte
