### ISSUE TITLE
Freetz-Info page: show version of installed packages, cgi, modules etc

### ISSUE THREAD

**Issue by WileC** [Freetz/freetz#130]
Es wäre schön, wenn man auf der Freetz-Info Seite sehen könnte, welche Version eines Packages oder eines CGI, oder whatever installiert ist.

z.B. **dnsmasq** wird zu **dnsmasq-2.80**

**Comment by er13** [comment]
Feel free to implement the feature and provide a patch (as pull-request). Until then no interest/time to implement it myself.
