### ISSUE TITLE
Wie mache ich ein neues Image?

### ISSUE THREAD

**Issue by Conan179** [Freetz/freetz#151]
Hallo erst mal.
Ich hab da mal eine blöde frage, wie erstelle ich ein neues Image?
Ich hab hier zuhause eine 7272 und eine 7390 mit schon älteren Freetz.
Jetzt möchte ich sie erneuern und weil meine Image noch auf der alten Seite waren, möchte ich neu anfangen, also wie mache ich das?

Endschuldigung für die Noob frage.

**Comment by JBBgameich** [comment]
Du checkst am beaten das neue git repository per `gut clone https://github.com/freetz/freetz` aus. Ab diesem schritt ist alles genau wie früher mit svn.

**Comment by Conan179** [comment]
Ah super, Ich danke dir!

**Comment by Conan179** [comment]
Oh noch eine kleine frage, wie wird ein update des geklonten Datenstand erstellt?

**Comment by JBBgameich** [comment]
`git fetch origin && git merge origin/master` oder alternativ `git pull` sollten reichen.

**Comment by Conan179** [comment]
Ok, Danke!

**Comment by er13** [comment]
So, Leute, das ist hier ein Bug-Tracking-System und kein Support-Forum!
