### ISSUE TITLE
Testing a 5490 (Fiber AON) but Fritz!OS rejects image

### ISSUE THREAD

**Issue by elmorti** [Freetz/freetz#200]
Hi folks,

Saw this PR recently https://github.com/Freetz/freetz/pull/145 (5491 Fiber GPON) and managed to "copy/paste" the affected files while adding the new model on my local build system, for 5490, using the latest AVM 5490 151.07.01 firmware.

Builds perfectly but the Fritz!OS rejects the image complaining being for a different box model. I have fiddling with the image content a bit and I can't seem to understand where is the logic to catch this. The only difference I can see with the install script on 5491 vs 5490 is the HWID (243 vs 223 respectively), however, I am using the firmware image from 5490. Any clue on how can I make Fritz!OS installs the custom built image so I can test it? Thanks!

**Comment by er13** [comment]
How exactly do you flash the image? Via AVM GUI? If so, then it won't work (at least for the very 1st time).

You have to use [eva_tools](https://github.com/PeterPawn/YourFritz/tree/master/eva_tools) from @PeterPawn [YourFritz](https://github.com/PeterPawn/YourFritz) project and an `.in-memory` image.

If you can read German then a lot of information could be found (in German) in [this](https://www.ip-phone-forum.de/threads/wie-verwende-ich-denn-nun-die-skript-dateien-aus-yourfritz-eva_tools.298591/) thread.

p.s. This is a bug tracking system and not a support forum. So I'm closing the issue. If you need support then feel free to ask questions in the thread linked above, also in English.
