### ISSUE TITLE
New release 2.4.8 of OpenVPN

### ISSUE THREAD

**Issue by stefanpuch** [Freetz/freetz#235]
Maybe someone can bump from 2.4.7 to 2.4.8?
Thanks in advance!

[openvpn.mk.diff.txt](https://github.com/Freetz/freetz/files/3803363/openvpn.mk.diff.txt)
[Config.in.diff.txt](https://github.com/Freetz/freetz/files/3803364/Config.in.diff.txt)

**Comment by berndy2001** [comment]
Why don't you make a pull request? I think this is the easiest way.
Please don't forget the CHANGELOG.

**Comment by stefanpuch** [comment]
You are right, that would probably be the easiest way, but unfortunately (at the moment) I haven't got a working git tree to create such a pull request. Therefore I  I just posted the to files (and missed the CHANGELOG)
