### ISSUE TITLE
Feedback- freetz-currentGit on my 7390

### ISSUE THREAD

**Issue by arjunae** [Freetz/freetz#27]
#Hey Kollegen,

..was pleasantly surprised that freetz is still actively maintained - so i gave master a try on my FB-7390.
First- spend some time searching through missing links to get some working image files. (Backport stuff /  Release kernel etc..) 

Ok. First: here's a persistent [GoogleDrive Link](https://drive.google.com/open?id=1J8mx83lgyK6eBNmT7YPY5qvASM3sj3wg) to a folder containing a zipped set of minimum dependencies that i gathered to get current freetz on the 7390.  (freetz-master/dl folder , all needed build and backport Images and a readme) Ed: just copying that will get you a working baseline for using freetz.

- Status 05.2x
"ancient" 05.2.x had some dropped patch hunks and the image endet in a boot-loop.

- Status 06.30
--> Runs flawlessly for 2Days with a freetz-custom-kernel 06.30. 
Used config: [7390_nfsrootable_sshd.config..txt](https://github.com/Freetz/freetz/files/1829415/7390_nfsrootable_sshd.config.txt)

### The "under Development" stuff 

- Status 06.51
-->News: Works in the follwing configuration: [7390_06.51-sshd-usbroot.config..txt](https://github.com/Freetz/freetz/files/1839570/7390_06.51-sshd-usbroot.config.txt)
If the AVM Webinterface does not work - copy attached logincheck.lua to usr/www/avm to get that fixed... [logincheck.lua.txt](https://github.com/Freetz/freetz/files/1836344/logincheck.lua.txt

- Status 06.83
"kids" removal patch failes.
Works flawlessly for about aMonth now (with no removal patches and USBRoot).
(some "alternate" configurations with removal patches showed to have WLAN Problems.)

### Appendix
A Pitfall when using usbroot - since that one uses fixed /dev/sd[abc...] pathes, conecting multiple Mass Storage Devices can lead to problems. (Definately- when you switch cabeling..) 

~ When stuff matures - there will be fix patches.
 
Finally, thanks for makin Freetz possible - 
Thorsten Kani

**Comment by er13** [comment]
Closing this ticket. The reported "remove patches"-problems are known and are not specific to 7390.
