### ISSUE TITLE
Support to FRITZ! Modem Box 3272?

### ISSUE THREAD

**Issue by eros23** [Freetz/freetz#274]
I have a FRITZ! Modem Box 3272.

I wanted to modify the software to get new features on it.

Anyone know if it is supported?
I'd like to experience something about it.

**Comment by er13** [comment]
S. [FIRMWARES](https://github.com/Freetz/freetz/blob/master/FIRMWARES) for the list of supported boxes.

3272 is expected to [work](https://github.com/Freetz/freetz/blob/0b1df5b68a8149eb3fec85b999809239d4c5eed9/FIRMWARES#L32).

**Comment by er13** [comment]
I'm closing the ticket as this is a bug tracking system. Please use [IPPF](https://www.ip-phone-forum.de/forums/freetz.525/) if you have any questions.
