### ISSUE TITLE
WLAN-Probleme bei Fritz!OS 7.01

### ISSUE THREAD

**Issue by DaniDD** [Freetz/freetz#286]
Hallo,

ich habe eine 7490er. Mit OS 6.93(oder4?) funktioniert alles super. Wegen verbessertem Mesh würde ich gerne OS 7.x  nutzen. Die Fritzbox startet und LAN funktioneirt auch. Leider gibt es aber mit WLAN Probleme. Die Zertifizierung funktioneirt, ich bekomme aber keine IP. Mit statischer IP komme ich auch nicht weiter.
Woran kann das liegen?
Vielen Dank

**Comment by PeterPawn** [comment]
Duplicate of #87

**Comment by f-666** [comment]
Exakt
