### ISSUE TITLE
Dnsmasq 2.84

### ISSUE THREAD

**Issue by Neustradamus** [Freetz/freetz#339]
@flosch-dev, @f-666: Can you update to 2.84?
- http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q1/014640.html

There was a bug in Dnsmasq 2.83.

Changelog:
- http://www.thekelleys.org.uk/dnsmasq/CHANGELOG

**Comment by WileC** [comment]
resolved with #341 ?

**Comment by Neustradamus** [comment]
@WileC: I think yes ^^
Thanks @flosch-dev, @f-666, and @WileC too.
