### ISSUE TITLE
avm download fails

### ISSUE THREAD

**Issue by Rothammel** [Freetz/freetz#345]
Download failed - "http://www.avm.de/de/Service/Service-Portale/fritzbox.7430/firmware/deutsch/FRITZ.Box_7430.146.06.83.image"  ->  error code 8

ERROR: Could not download firmware image. See http://trac.freetz.org/wiki/FAQ#Couldnotdownloadfirmwareimage for details.
make: *** [dl/fw/FRITZ.Box_7430.146.06.83.image] Fehler 3

**Comment by er13** [comment]
There is nothing we can do about it. AVM removed this firmware version from their servers.

Hint: check this thread https://www.ip-phone-forum.de/threads/suche-firmware-recover-images.119856/
