### ISSUE TITLE
790AX does not work

### ISSUE THREAD

**Issue by hookdr** [Freetz/freetz#354]
Hello fda77 , build for 790AX builds no Image, just a oscam binary, 7590 7560 are ok

**Comment by f-666** [comment]
please address this issue to the freetz-ng project

**Comment by fda77** [comment]
Auch dort gibt es kein oscam binary

**Comment by hookdr** [comment]
sorry, meinte die oscam bei 7590 und 7560 wird eingebaut. Bin n mal kein Linux Spezialist
