### ISSUE TITLE
Please switch the leading VCS to Git

### ISSUE THREAD

**Issue by PeterPawn** [Freetz/freetz#38]
I'm pleading for, that Git will become the leading VCS for Freetz *as soon as possible* - and that means, within days and not within weeks.

Why?

Git is simply better suited for distributed changes and there are some (active) forks already, "outside in the wild". It's much easier to prepare, adjust and apply a pull request from Git and it's simpler to incorporate upstream changes into an own local repository.

The currently necessary SVN-to-Git conversion by @mhei becomes superfluous and "push" messages from GitHub will get the name of the real publisher ... and it becomes possible, to use author-signed commits (with review and co-signing options) - a big advantage compared to the current situation, where only the SVN credentials protect the integrity of the "trunk" (aka 'master' branch), because any commit from SVN will be pushed to GitHub.

*And at the same time it should become practice, that "work in progress" changes are gathered in an own, local clone of the upstream (master) branch and - in most cases - in an own fork or at least a "working branch" of the public repository, too. When they're completed or at least temporarily finished, they'll get merged with the master branch.*

This is my main interest (or call it idea or wish or plead) ... it's a terrible situation, if the master branch gets many changes in short intervals (like today) and no-one of the "forkers" may know, whether and when such changes are completed up to a point, where merging with and rebasing to the upstream master makes sense for their own branches.

I'm coupling this wish with the needs to switch to Git, because I don't know, whether the current solution, to synchronize SVN to GitHub, is able to work with (additional new) branches on the SVN side.

I know, that it's some work to switch to another VCS in the own development environment - but it looks now, as if the SVN server were the last instance, which is really running on the (bare-metal) server of @Lars. And I believe, the reliability of GitHub servers is somewhat higher (looks like I'm not the only one) and the existence of distributed repositories is another and additional protection against this "single point of failure", from the currently used SVN server (and if GitHub is really more and more under stress and gets attacked in the future).

Some actions in the last week have shown, that such workflow changes need one clean, but still coordinated cut - if changes on the Git side get not merged with the SVN trunk during publishing (bi-directional), it's not an option for *any* developer (with write access to the repositories of the "Freetz" organization), to publish own changes on the Git-side of synchronization.

**Comment by olistudent** [comment]
Hello Peter.

Because I'm totally off from the development I can't evaluate the impact of the switch. If it's only a commitment to checkin into git(hub) and no more into svn then the switch shouldn't be more effort than  switching the plugin in the IDE like you mentioned.

As we are moving away from Trac we do not need to think about things like the svn-post-commit-hook...

Regards,
Oliver

**Comment by kriegaex** [comment]
I guess the most consequent thing to do would be to just shut down the SVN service on the server and deactivate auto-start. The post-commit hook would not do anything anymore as a consequence, of course. Then maybe someone could edit the wiki (in the imported pages section on GitHub) and adjust all info concerning check-out, commit, download etc. to GitHub as well. (Busy, no time to think it through completely.) Just let the rest escalate, i.e. if any developer cannot commit anymore etc., they will somehow raise their hands and let us know.

**Comment by PeterPawn** [comment]
The most active person with write access is obviously @er13 ... as far as I remember (or may see in the last six months), most others only maintain some packages, which were created by themselves in the past.

I don't know, what's the real effort for Gene, if he switches to Git/GitHub - but if we're taking the expectations for the near future into account (possibly AVM will publish FRITZ!OS 7 in less than five weeks - CeBIT and ANGA COM are on the agenda), then a stable VCS will become even more important, if changes have to be published and many Freetz users have to re-build their images for the current version (I assume, that it will be supported at this time, the first steps from @er13 are visible already).

And if L.F. will be absent for a longer time (the holiday season is near, too) and the SVN server crashes, there's no other option anymore than switching to Git (or to wait until the server gets back in order anytime). 

Due to my own experience I can say, such changes are much easier to apply to the own workflow, if they're "voluntary".

But even if @er13 takes some more time to switch ... in my opinion, it should be possible to change the DNS entries independent of it. A small HTTP server with (static) redirections for "{www,wiki}.freetz.org" could do this job for most users with their (web-)browsers. 

Any changes to Wiki content are still important and have to be done - but it's obviously useless, if the Wiki shows the right (old) solution or first steps, but the mentioned services aren't reachable (most of the time).

Some additions to the freetz.github.io repo are easy ... a short page (German should be fine and sufficient as a first step) with an explanation, that the project was moved to Git/GitHub ... and everybody should know, how to clone the repository (instead of "svn checkout") or he/she has to learn it now. 

A link ti this page may then be placed in front of any "svn" command reference in the Wiki pages and the original text may be kept with strikethrough formatting - it's not a really pretty solution, but it works and - more important - it's quickly done (with write access). 

Because changes to the other repository do not harm the synchronization of "freetz" (from SVN), it's a solely independent task to do and could get started immediately.

**Comment by kriegaex** [comment]
Just deactivate SVN, make a hard cut. Whoever wants to contribute to Freetz and does not have write access can fork the project and provide PRs while at the same time asking for direct repo access.

Any volunteers for the GitHub pages?

BTW, those wiki pages were quite suboptimal when I last checked. As far as I remember, some links did not work, content (images) was missing. Maybe this has been fixed already by an improved import script, I have not checked (busy).

**Comment by nyov** [comment]
You guys know that for any die-hard SVN fans, GitHub supports [this](https://help.github.com/articles/support-for-subversion-clients/)? For a long time, now.

**Comment by olistudent** [comment]
As SVN is shut down now can we close this issue or is here anything todo? Ah, the wiki pages on freetz.github.io...
