### ISSUE TITLE
AVM-Forwarding broken in Fritz!OS-6.8x (7490)

### ISSUE THREAD

**Issue by tkurbad** [Freetz/freetz#5]
Hi,

I just upgraded my box to 6.80 and came to realize that my port forwarding to 443 on the box itself (placed in an earlier version via AVM-Forwarding) was gone.

After re-adding the forwarding, it is again gone from the list as soon as the box is rebooted.

I've opened the web-interface of the box via 444, so I guess AVM now deliberately closes port 443 if it's not in use (from the original firmware's perspective).

Any chances of overcoming this situation?

EDIT: All forwardings besides 443 work as expected, e.g. 22 TCP for SSH.

Thanks,
Torsten

**Comment by PeterPawn** [comment]
Look at the IPPF site (README.md contains the link) and locate the thread, where exactly this question was discussed only a short time ago (and it was answered there, that means, it's worth the reading).

**Comment by tkurbad** [comment]
Ok, should someone else have this problem and no time to read through a bunch of threads on the forum, here's the solution:

Port forwardings from port 443 have to go into the `voip_forwardrules = ".....",` section of /var/flash/ar7.cfg.

If I find the time, I'll try to write a patch for AVM-Forwarding that takes this into account.

Best,
Torsten
