### ISSUE TITLE
Crash when using Tun/Tap with Fritz!OS7 (e.g. OpenVPN)

### ISSUE THREAD

**Issue by JokerGermany** [Freetz/freetz#51]
For Tracking purpose
https://www.ip-phone-forum.de/threads/fritz-os7-openvpn-auf-7590-kein-tun-modul.300433/
http://freetz.org/ticket/2979

**Comment by er13** [comment]
One ticket (http://freetz.org/ticket/2979) is more than enough, thus closing here.

**Comment by Simon0Harms** [comment]
gow can i track it at freetz.org?

**Comment by f-666** [comment]
it is not possible to track tickets in the freetz trac
