### ISSUE TITLE
Aufruf von "fwmod"

### ISSUE THREAD

**Issue by PeterPawn** [Freetz/freetz#54]
Bei speziellen Einstellungen in der Konfiguration:
```shell
FREETZ_FWMOD_SKIP_UNPACK=y
FREETZ_FWMOD_SKIP_MODIFY=y
FREETZ_FWMOD_SKIP_PACK=y
# FREETZ_FWMOD_USBROOT is not set
# FREETZ_FWMOD_NFSROOT is not set
```
(wenn man nur die Freetz-Toolchain und ausgewählte Pakete erzeugen will, aber kein Image) wird trotzdem "fwmod" aufgerufen, was dann mangels Aktion mit dem Help-Screen und einem Fehlercode reagiert (und in der Folge mit einem Abbruch des "make"-Laufs).

**Comment by er13** [comment]
Im menuconfig wird das doch aber deutlich als [Invalid fwmod configuration](https://github.com/Freetz/freetz/blob/master/config/ui/fwmod.in#L8) gekennzeichnet.

**Comment by PeterPawn** [comment]
Das wird bei mir nicht als Kommentar angezeigt im Menü, wenn ich die Einstellungen vornehme:
![fwmod_no_action](https://user-images.githubusercontent.com/16480869/47752350-7de17c00-dc94-11e8-82fb-482e1cdd1680.PNG)
Außerdem wäre es m.E. einfacher, dann den Aufruf von "fwmod" nicht auszuführen.

**Comment by er13** [comment]
Stand jetzt ist es kein "gewollter Anwendungsfall". Aber es spricht auch nicht wirklich was dagegen, auf den Aufruf von fwmod bei diesen Einstellungen zu verzichten. Ich schaue es mir an. Allerdings nicht heute.
