### ISSUE TITLE
libdb compile error

### ISSUE THREAD

**Issue by programminghoch10** [Freetz/freetz#56]
Hello, I was trying to create some usb root images for several boxes, but in this case (4040) I can't decipher the log and deselect the according package to get it working, because it seems to be an background error.
Here is the .[config.txt](https://github.com/Freetz/freetz/files/2550734/config.txt)
The error log is from today, when I was trying it again with the latest checkout (5.11.2018).
[error.txt](https://github.com/Freetz/freetz/files/2550737/error.txt)
I saved all the scrollback that was available when the problem came up for the first time.
[scrollback.txt](https://github.com/Freetz/freetz/files/2550738/scrollback.txt)
Because I can't analyse the problem properly, the title of this issue might be misleading, correct me if needed.

**Comment by olistudent** [comment]
Hi. 

The package throwing the error is db-4.8.30 / libdb.
