### ISSUE TITLE
SSH / Telnet lost. Can't install freetz anymore

### ISSUE THREAD

**Issue by zolant** [Freetz/freetz#59]
Hello,

Sorry, I don't speak German. Let me describe the problem. Yesterday, I updated freetz firmware to version 6.53, everything was good. However, I forgot to change autoupdate and overnight it was automatically updated to the latest 7.01 original avm.de stock version! 

Now, I don't have telnet/ssh access, also I can't update to freetz anymore.  Please help!
I want my freetz back!
Looking for any workaround.

**Comment by programminghoch10** [comment]
What do you mean with you can't install freetz anymore?
Also more generic information would help...
Which box are you talking about?

**Comment by olistudent** [comment]
Perhaps it would be better to open a thread in IP-Phone-Forum. There will be a better place to get help. Issue tracker on github is not the right place for this...
