### ISSUE TITLE
4020: Update to 147.07.01

### ISSUE THREAD

**Issue by programminghoch10** [Freetz/freetz#62]
Sorry to bug you, 
I want to mod my 4020 with Fritz!OS 7 and I'm waiting for the sources to be updated for over a month now.
I am currently unable to do that myself due to lack of knowledge.
Isn't there any way to automate that process?

**Comment by PeterPawn** [comment]
The open-source package for 147.07.01 seems not to be available yet.

http://osp.avm.de/fritzbox/fritzbox-4020/

Send a request to AVM first and ask them, to publish the sources.

**Comment by programminghoch10** [comment]
> Look into the `info_de.txt` file (at its end - the file is usually bundled with new firmware and contains a list of changes at its beginning) to get an idea, which e-mail address should be used.

Well I haven't found this file, but I have asked them using their normal way of getting support.
Answer is pending

Maybe I was asking a bit unclear so I'll try to ask in german.

Inwiefern braucht freetz den source code, warum reichen nicht für ein paar simple Aktionen auch das entpacken des image, denn soweit ich das verstehe wird immer nur der image pfad aktualisiert wenn zb ein neues Labor herauskommt. Und warum automatisiert man den prozess nicht sodass freetz selbstständig nach neuen laborversionen suchen kann.

**Comment by PeterPawn** [comment]
Die Adresse ist irgendwas mit fritzbox_info@avm.de ... landet m.W. bei etwas anderen Bearbeitern.

Für die meisten Pakete braucht Freetz schon die Quellen für den korrekten Kernel (die 4020 verwendet ab 07.0x wohl einen Kernel 4.4.60 und die verfügbaren Kernel-Quellen sind noch 2.6.32 - bei der C-Library und der BusyBox sieht das vermutlich ähnlich aus, ohne daß ich da jetzt nachgesehen hätte), damit die Pakete passend übersetzt werden können. 

Solange sich die Kernel-Version nicht entscheidend ändert, kann man da auch ältere verwenden ... aber der Sprung zur 4.4.60 (iirc der "modernste" Kernel, den AVM offiziell in einer Box verwendet) bedingt eben, daß man erst mal die richtigen Quellen braucht.

Danach ist es tatsächlich machbar (zumal die Komponenten auch für eine sichere Handhabung vorlägen, wenn man auf "juis_check" und "check_signed_image" zurückgreift), einen zusätzlichen Punkt "aktuelle Laborversion" einzuführen, solange sich nichts Entscheidendes zwischen den Laborversionen ändert. 

Im Moment paßt dieses Vorgehen halt nicht zu den Interna von Freetz (z.B. muß für den "Firmware-Download" der MD5-Hash des Images bekannt sein) und man muß das "außen herum" automatisieren, wenn man so etwas gerne hätte.

Das ist eigentlich auch kein größeres Problem ... man muß nur nach dem "juis_check"-Aufruf die Version von AVM laden, im richtigen Ordner ablegen (dl/fw) und die Prüfsumme sowie den Namen in die ".config" so einfügen, als wäre das über den Menüpunkt "Firmware source" (nicht zu verwechseln mit dem OpenSource-Paket, das zu verwenden ist - entscheidend ist hier das Symbol `FREETZ_DL_SOURCE`) erfolgt.

Macht man das mit einem eigenen Skript vor dem Aufruf von "make", kann man sich diese "aktuelle Labor-Version"-Funktion auch leicht selbst einbauen, ohne an den anderen Mechanismen (Download, Prüfung) irgendetwas ändern zu müssen.

**Comment by programminghoch10** [comment]
Die 7.01 sources der 4020 sind jetzt verfügbar:
http://osp.avm.de/fritzbox/fritzbox-4020/

**Comment by programminghoch10** [comment]
Could someone please update the sources?

**Comment by programminghoch10** [comment]
please someone?
i dont know how to do it myself

**Comment by PeterPawn** [comment]
Das Problem ist u.a. auch, daß niemand (von denen, die im Moment aktiv sind) die Zugangsdaten für die Mirror-Server hat - siehe hier: https://github.com/Freetz/freetz/pull/112#issuecomment-470777453

Bei Freetz würde man jetzt das Source-Paket von AVM auseinandernehmen und ein neues Archiv mit den Kernel-Quellen erstellen, welches dann auf die Mirror-Server geladen wird und von dort für die Freetz-Benutzer erreichbar ist.

Ohne die Zugangsdaten muß man jede Menge zusätzlich umstellen, um - als Beispiel - einen weiteren Spiegel-Server hinzuzufügen - da sehe ich persönlich im Moment kein Land.

Auch hat wohl keiner der im Moment Aktiven eine eigene 4020 - mithin ist der "Druck" auch nicht wirklich groß, selbst wenn man die Rufe der Freetz-Benutzer vernimmt.

Wie wär's denn, wenn Du es selbst probierst, einen Fork und den passenden Branch aufmachst und dann einen PR dafür als "draft" ... darin kann man Dir dann weiterhelfen, wenn Du irgendein Problem nicht gelöst bekommst.

Das Problem mit den fehlenden Zugangsdaten für die Mirrors könnte man - für die Phase, bis die Änderungen komplett sind - durch den vorherigen "Download" (sprich: durch manuelles Kopieren der Datei in den "dl"-Ordner) umschiffen.

Am Ende ist das eigentlich fast alles nur "Verwendung" anderer Programme - man muß selbst nichts wirklich programmieren und in erster Linie die passenden Einstellungen in den Kconfig-Dateien vornehmen ... ich weiß gar nicht, ob bei der 4020 der Wechsel auf den neuen Kernel schon vor der 07.0x erfolgte oder auch erst mit dieser Version Gestalt annahm. Da das aber auch MIPS ist, sollte das kein wirkliches Problem darstellen - die Kernel-Patches dürften dieselben sein.

**Comment by olistudent** [comment]
Ich lade das Paket gerne hoch, wenn es jemand zusammen packt. Daran soll es nicht scheitern...

**Comment by programminghoch10** [comment]
Vielen Dank für die Info, das Problem war mir nicht bewusst.
Soweit ich weiß geht das mit den Archiv (wenn es sich dabei um einen precompiled toolchain handelt) eh nicht weil irgendetwas anders ist.
[#43 (comment)](https://github.com/Freetz/freetz/issues/43#issuecomment-411846643)
Und die Box benutzt den neuen Kernel, weshalb ich mich ja schon darum gekümmert habe und AVM gebeten hab deren neuen Kernel für die 4020 zu veröffentlichen.
@olistudent Ich helfe da gerne

**Comment by PeterPawn** [comment]
> wenn es sich dabei um einen precompiled toolchain handelt

Nein, es handelt sich dabei um einen "Auszug" aus dem OpenSource-Paket von AVM, welches neben den Kernel-Quellen noch jede Menge andere Dateien (dabei auch viel Schrott aus uralten und längst nicht mehr relevanten Versionen) enthält. 

Die Kernel-Quellen sind so um die 80 MB in gepackter Form ... vergleich' das mal mit der Größe der Download-Pakete bei AVM: http://osp.avm.de/fritzbox/fritzbox-4020/

**Comment by programminghoch10** [comment]
Das sind bei dem Paket etwa 417 MB, aber wenn ich dadurch zu Erfolg komme dann werde ich den Speicher investieren. Inwiefern kann ich also mit dem vom AVM bereitgestellten Paket etwas anfangen und zu meinem Freetz 7.01 kommen?

**Comment by PeterPawn** [comment]
In dem Paket von AVM sind u.a. die Kernel-Quellen enthalten. Vergleiche einfach das OSS-Paket von AVM für die ältere Version mit dem Teil, der in Freetz als "4020-irgendwas-release_kernel-irgendwas" von einem der Spiegel-Server geladen wurde und Du weißt schon mal, welchen Teil des (neuen) AVM-OSS-Pakets Du als "*release_kernel*"-Paket bereithalten mußt - ich weiß gerade nicht, ob das in Freetz tatsächlich 1:1 die Datei aus dem AVM-Paket ist. Deshalb ja der Rat, das für die ältere Version zu vergleichen. Diese Datei legst Du dann bei Dir in den Ordner "dl/fw" (korrekte Checksummen in den Kconfig-Dateien nicht vergessen, sonst werden die beim "make" gleich wieder entsorgt) und umgehst damit (bei Dir) erst mal das Mirror-Problem.

Dann ein "grep" über die Dateien in "config" mit dem Namen der (alten) Download-Datei und Du hast schon mal die Datei gefunden, in der die Zuordnung der Kernel-Quellen und der Firmware-Images erfolgt.

Da fügst Du dann - analog zu anderen Boxen mit der 07.01 - die neuen Konfigurationseinstellungen für die 4020 mit 07.01 hinzu und das war's dann vermutlich auch schon in weiten Teilen. 

Nur klingt das jetzt deutlich kürzer, als es am Ende wohl sein wird - das ist also nur "die Idee" für den Anfang, die Dir vielleicht fehlt.

**Comment by olistudent** [comment]
Naja, ganz so einfach ist es nicht...

Es muss erstmal die 07.01 Firmware integriert werden. Die Sourcen kommen dann erst später ins Spiel...

Beispiel von anderer Box:
https://github.com/Freetz/freetz/commit/daa409c83b6b309e9b5392467b6da373208b16a8#diff-e59b0bd881c6c14a87bda61a83e30d3d

**Comment by PeterPawn** [comment]
@programminghoch10 
Ich hatte schon wieder vergessen, daß hier ja ein 4.4-Kernel mit der 07.01 zum Einsatz kommt ... gut möglich, daß der tatsächlich noch neue Patches braucht (wobei das bei AVM eigentlich alles dabei sein sollte, aber grau ist an dieser Stelle alle Theorie, wie die Vergangenheit zeigt).

Auf alle Fälle braucht's dann für die 4020 auch noch die passende Konfiguration für die uClibc-ng - denn auch diese wird dann "neu" sein und wenn sich die bisherige Unterstützung für die 4020 auf einen 2.6.32-Kernel und die uClibc 0.9.33 gründet (das ist das, was ich beim Blick in die Dateien gefunden habe: https://github.com/Freetz/freetz/blob/master/config/avm/source.in#L84), dann ist das doch deutlich mehr an Arbeit, als ich ursprünglich angenommen hatte.

Aber das soll Dich keinesfalls davon abhalten, es zu versuchen ... man kann an der Stelle nur lernen.

**Comment by olistudent** [comment]
Ich hab mal das abgetippt was mir so unter gekommen ist. Jetzt bin ich mit meinem Core2Duo am Ende. Da wäre die Toolchain vielleicht morgen irgendwann fertig...

```diff
diff --git a/FIRMWARES b/FIRMWARES
index cec50dac8..9c62f5510 100644
--- a/FIRMWARES
+++ b/FIRMWARES
@@ -62,6 +62,7 @@ Currently supported boxes and firmwares
 
 * Fritz!Box 4020
 	* 147.06.83 rev43440 (German & International)
+	* 147.07.01 rev64348 (German & International)
 
 * Fritz!Box 4040 (EXPERIMENTAL)
 	* 155.07.01 rev61489 (German & International)
diff --git a/config/avm/availability.in b/config/avm/availability.in
index aea870b57..0aa76d30f 100644
--- a/config/avm/availability.in
+++ b/config/avm/availability.in
@@ -198,6 +198,7 @@ config FREETZ_AVM_HAS_FIRMWARE_07_0X
 		( FREETZ_TYPE_LANG_DE && ( \
 			FREETZ_TYPE_1750 || \
 			FREETZ_TYPE_3490 || \
+			FREETZ_TYPE_4020 || \
 			FREETZ_TYPE_4040 || \
 			FREETZ_TYPE_6490 || \
 			FREETZ_TYPE_6590 || \
diff --git a/config/avm/compiler.in b/config/avm/compiler.in
index 12d2a9bb5..2a7e47175 100644
--- a/config/avm/compiler.in
+++ b/config/avm/compiler.in
@@ -33,7 +33,7 @@ config FREETZ_AVM_GCC_4_8
 		(FREETZ_SYSTEM_TYPE_AR934x    && FREETZ_AVM_VERSION_06_2X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_IKS       && FREETZ_AVM_VERSION_06_2X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_QCA955x   && FREETZ_AVM_VERSION_06_8X_MAX) || \
-		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_06_8X_MIN) || \
+		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_06_8X_MAX) || \
 		(FREETZ_SYSTEM_TYPE_VR9       && FREETZ_AVM_VERSION_06_9X_MAX)
 
 # AVM never used it
@@ -48,6 +48,7 @@ config FREETZ_AVM_GCC_5
 		(FREETZ_SYSTEM_TYPE_IPQ40xx   && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_PUMA6     && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_QCA955x   && FREETZ_AVM_VERSION_07_0X_MIN) || \
+		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_VR9       && FREETZ_AVM_VERSION_07_0X_MIN)
 
 config FREETZ_AVM_GCC_3_4_MIN
diff --git a/config/avm/kernel.in b/config/avm/kernel.in
index ffefb13e5..691d07bd0 100644
--- a/config/avm/kernel.in
+++ b/config/avm/kernel.in
@@ -105,7 +105,8 @@ config FREETZ_KERNEL_VERSION_4_4_60
 	default y
 	depends on \
 		(FREETZ_SYSTEM_TYPE_IPQ40xx && FREETZ_AVM_VERSION_07_0X_MIN) || \
-		(FREETZ_SYSTEM_TYPE_QCA955x && FREETZ_AVM_VERSION_07_0X_MIN)
+		(FREETZ_SYSTEM_TYPE_QCA955x && FREETZ_AVM_VERSION_07_0X_MIN) || \
+		(FREETZ_SYSTEM_TYPE_QCA956x && FREETZ_AVM_VERSION_07_0X_MIN)
 
 config FREETZ_KERNEL_VERSION_4_4
 	bool
diff --git a/config/avm/source.in b/config/avm/source.in
index 875ca991a..36617c380 100644
--- a/config/avm/source.in
+++ b/config/avm/source.in
@@ -83,6 +83,8 @@ config FREETZ_AVM_SOURCE_6590_07_02
 # QCA956x
 config FREETZ_AVM_SOURCE_4020_06_50
 	bool
+config FREETZ_AVM_SOURCE_4020_07_01
+	bool
 
 # UR8
 config FREETZ_AVM_SOURCE_7270_04_86
@@ -159,6 +161,7 @@ config FREETZ_AVM_SOURCE_ID
 	default "6590_07.02"    if FREETZ_AVM_SOURCE_6590_07_02
 # QCA956x
 	default "4020_06.50"    if FREETZ_AVM_SOURCE_4020_06_50
+	default "4020_07.01"    if FREETZ_AVM_SOURCE_4020_07_01
 # UR8
 	default "7270_04.86"    if FREETZ_AVM_SOURCE_7270_04_86
 	default "7270_05.21"    if FREETZ_AVM_SOURCE_7270_05_21
@@ -249,6 +252,7 @@ config FREETZ_AVM_SOURCE_FOR_SYSTEM_TYPE_QCA955x
 config FREETZ_AVM_SOURCE_FOR_SYSTEM_TYPE_QCA956x
 	depends on FREETZ_SYSTEM_TYPE_QCA956x
 	select FREETZ_AVM_SOURCE_4020_06_50 if FREETZ_AVM_VERSION_06_8X
+	select FREETZ_AVM_SOURCE_4020_07_01 if FREETZ_AVM_VERSION_07_0X
 	bool
 
 config FREETZ_AVM_SOURCE_FOR_SYSTEM_TYPE_UR8
diff --git a/config/avm/uclibc.in b/config/avm/uclibc.in
index 54c9484cb..513f29eaa 100644
--- a/config/avm/uclibc.in
+++ b/config/avm/uclibc.in
@@ -42,7 +42,7 @@ config FREETZ_AVM_UCLIBC_0_9_33
 		(FREETZ_SYSTEM_TYPE_IKS       && FREETZ_AVM_VERSION_06_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_PUMA6     && FREETZ_AVM_VERSION_06_8X_MAX) || \
 		(FREETZ_SYSTEM_TYPE_QCA955x   && FREETZ_AVM_VERSION_06_8X_MAX) || \
-		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_06_8X_MIN) || \
+		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_06_8X_MAX) || \
 		(FREETZ_SYSTEM_TYPE_VR9       && FREETZ_AVM_VERSION_06_9X_MAX)
 
 config FREETZ_AVM_UCLIBC_1_0_14
@@ -53,6 +53,7 @@ config FREETZ_AVM_UCLIBC_1_0_14
 		(FREETZ_SYSTEM_TYPE_IPQ40xx   && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_PUMA6     && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_QCA955x   && FREETZ_AVM_VERSION_07_0X_MIN) || \
+		(FREETZ_SYSTEM_TYPE_QCA956x   && FREETZ_AVM_VERSION_07_0X_MIN) || \
 		(FREETZ_SYSTEM_TYPE_VR9       && FREETZ_AVM_VERSION_07_0X_MIN)
 
 config FREETZ_AVM_UCLIBC_NPTL_ENABLED
diff --git a/config/mod/download.in b/config/mod/download.in
index fd39cdb2b..3b0a810d2 100644
--- a/config/mod/download.in
+++ b/config/mod/download.in
@@ -216,6 +216,7 @@ menu "Override options"
 		default "@AVM/{fritzbox-3490/{other,belgium}/fritz.os,fritzbox.3490/firmware/{english,belgium}}"                   if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_3490 && FREETZ_TYPE_LANG_EN && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "@AVM/{fritzbox-4020/{other,deutschland}/fritz.os,fritzbox.4020/firmware/deutsch}"                         if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_06_8X
+		default "@AVM/{fritzbox-4020/{other,deutschland}/fritz.os,fritzbox.4020/firmware/deutsch}"                         if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "@AVM/fritzbox-4040/{other,deutschland}/fritz.os"                                                          if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4040 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
@@ -452,6 +453,7 @@ menu "Override options"
 		default "FRITZ.Box_3490.en-de-es-it-fr-pl.140.07.01.image"              if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_3490 && FREETZ_TYPE_LANG_EN && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "FRITZ.Box_4020.de-en-es-it-fr-pl.147.06.83.image"              if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_06_8X
+		default "FRITZ.Box_4020.de-en-es-it-fr-pl.147.07.01.image"              if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "FRITZ.Box_4040.de-en-es-it-fr-pl.155.07.01.image"              if FREETZ_TYPE_FIRMWARE_FINAL && FREETZ_TYPE_4040 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
@@ -691,6 +693,7 @@ menu "Override options"
 		default "5427f2fd79c2c88a4d947ac874693fe6"  if FREETZ_TYPE_3490 && FREETZ_TYPE_LANG_EN && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "a107c164581c60a87659bcfeba3a238b"  if FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_06_8X
+		default "873dab3e4d936920a8bb590120a7b6fe"  if FREETZ_TYPE_4020 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
 		default "56fa9f6089361c2e046229e448e1af1a"  if FREETZ_TYPE_4040 && FREETZ_TYPE_FIRMWARE_07_0X
 		#
[4020_07.01.patch.zip](https://github.com/Freetz/freetz/files/2949846/4020_07.01.patch.zip)

```

**Comment by programminghoch10** [comment]
Sry dass ich da etwas unerfahren bin, wie patche ich mit der .patch file das Verzeichnis,
es sagt immer "can't find file to patch at input line 5"
ich hab 2 verzeichnisse a und b beide mit dem aktuellen MASTER branch drin

**Comment by JBBgameich** [comment]
Es sollte funktionieren den patch in eine Datei z.B. diff.patch zu kopieren und dann git apply diff.patch auszuführen.

**Comment by programminghoch10** [comment]
das hat geklappt, danke!
Der Prozess des Kompilierens arbeitet schon :)

**Comment by programminghoch10** [comment]
rm -f -r source/kernel/ref-qca956x-4020_07.01
mkdir -p source/kernel/ref-qca956x-4020_07.01/linux-2.6.32
 unpacking...  applying patches... #
#kernel version specific patches
    applying patch file make/linux/patches/2.6.32.61/001-drivers_dsl_kconfig.patch
    patching file linux-2.6.32/drivers/dsl/Kconfig
    patching file linux-2.6.32/drivers/dsl/Makefile.26
    patching file linux-2.6.32/drivers/Kconfig
    Hunk #1 FAILED at 116.
    1 out of 1 hunk FAILED -- saving rejects to file linux-2.6.32/drivers/Kconfig.rej
    ----------------------------------------------------------------------
ERROR: modpatch: Error in patch-file make/linux/patches/2.6.32.61/001-drivers_dsl_kconfig.patch
make/linux/kernel.mk:38: recipe for target 'source/kernel/ref-qca956x-4020_07.01/.unpacked' failed
make: *** [source/kernel/ref-qca956x-4020_07.01/.unpacked] Error 2

Da liegt das erste problem :/

**Comment by PeterPawn** [comment]
Offensichtlich die falsche Kernel-Version, denn 2.6.32 verwendet die 07.01 ja nicht.

Nun hat @olistudent Dir ja einen Teil der Patches bereitgestellt ... aber Dir jetzt von Problem zu Problem zu helfen, wird wohl nur dann klappen, wenn die Leute hier eine Vorstellung haben, wie "das Freetz" jeweils gerade aussieht, mit dem Du arbeitest.

Wenn Du das in einen (GitHub-)Fork packst, dort einen Branch einrichtest für 4020_07_01 und da die geänderten Dateien bereitstellst, kann sich das jeder auschecken bzw. es sich (mit dem GitHub-GUI) ansehen. 

Das wäre zumindest "die übliche Vorgehensweise", weil sich ansonsten jeder selbst das System so zurechtpatchen müßte, wie Du das getan hast ... irgendwann kann das dann aber keiner mehr verfolgen, welcher Patch nun richtig war und verwendet werden muß, welcher geändert werden sollte und welcher gar nicht gebraucht wird. 

Zwar wäre es im Moment noch leicht (solange es nur den Patch von @olistudent gibt), aber schon beim Versuch der Korrektur des Problems der falschen Kernel-Version kommt der nächste Patch hinzu und es werden in der Zukunft garantiert nicht weniger.

Deshalb bin ich (persönlich) auch kein großer Fan davon, daß man nur Patch-Files für andere bereitstellt (außer als "Änderungsvorschlag", den derjenige dann selbst in seinen Fork übernimmt und ins Repo pusht) ... das geht ja nun in GitHub deutlich besser und man kann anderen gleich einen passend gepatchten Stand anbieten (in einem Branch des eigenen Forks vom Stamm-Repo), in dem diese einfach "browsen" können, was den aktuellen Code-Stand angeht, sich die ausgeführten Änderungen (in der Commit-Liste) ansehen können und notfalls auch selbst genau denselben Stand auschecken und testweise übersetzen können, wenn z.B. mal eine Fehlernachricht nicht so richtig aussagekräftig oder zu stark gekürzt wiedergegeben ist.

Wie gesagt ... spätestens nach dem dritten oder vierten Patch wird das sehr schwer bis aussichtslos, das alles anhand von Text in so einer Issue verfolgen zu wollen - und es ist vor allem so absolut unnötig. Genau dafür gibt es ja SCM, damit man (auch gemeinsam) an Neuem arbeiten kann, ohne Altes zu sehr zu verändern und damit unbrauchbar zu machen ... und dank GitHub (oder anderen GUI) geht das notfalls sogar alles im Browser (zumindest das "Gucken").

**Comment by olistudent** [comment]
@PeterPawn 
Ja, sorry. Ich hätte es gleich richtig machen sollen. Aber die Zeit... :-)

Hab den Commit von freetz-ng übernommen.

**Comment by heini66** [comment]
ja, ja... immer diese studendten ... ;)
schön, das du wieder onboard bist....

Am So., 17. März 2019 um 17:31 Uhr schrieb Oliver Metz <
notifications@github.com>:

**Comment by fda77** [comment]
4020
Ich finde das ganz schön dreist. Immerhin haben sich die Freetz-Entwickler von mir mit "wir [Freetz-Entwickler] wollen nichts von dir [cuma/fda], wir können eh alles besser" getrennt!
Daher bitte ich zuerst https://github.com/Freetz/freetz/issues/89 zu klären. Was spricht dagegen dass ich hier Schreibrechte bekommen, wenn die commits eh übernommen werden?
Zumindest den Git-hash und die Quell-URL hätte man angeben können: https://trac.boxmatrix.info/freetz-ng/changeset/15256/freetz-ng

**Comment by programminghoch10** [comment]
I tested it, it works now!
Thanks to all who helped!
Also just saying, 7.01 (also the avm original version) has problems starting if the previous version had usbroot enabled.
