### ISSUE TITLE
Build Freetz for Fritz!Box 7113

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [Freetz/freetz#67]
Is it possible to build a current Freetz version for 7113? I don't need DSL (just Internet over LAN1) and telephone would be optional.

Also, what AVM firmware would such a build be based on?

PS: It would just be used as an Router + Access Point in a dormitory.

**Comment by programminghoch10** [comment]
If you look into the file named FIRMWARES you get your answer:
* Fritz!Box Fon WLAN 7113
	* 60.04.68 rev17260
	* 90.04.86 rev27557 (International, Annex A)
	* Alien 7170

**Comment by olistudent** [comment]
If you need further assistance of building a freetz image please head over to IP-Phone-Forum->Freetz section.
