### ISSUE TITLE
tvheadend v HTS Tvheadend 4.2.8-4~g9f7ab681a docker

### ISSUE THREAD

**Issue by halfagascan** [Freetz/freetz#68]
HTS Tvheadend 4.2.8-4~g9f7ab681a
debian Linux tanana 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
docker -v Docker version 18.09.1, build 4c52b90
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
f0b6a8da8fcf        linuxserver/tvheadend:release-4.2   "/init"                  4 hours ago         Up 2 hours          0.0.0.0:9981-9982->9981-9982/tcp                   tvheadend
2d55a3cc098b        jellyfin/jellyfin                   "/bin/sh -c 'dotnet …"   5 days ago          Up 5 hours                                                             jellyfin1
b7bad36dbddd        portainer/portainer                 "/portainer -H unix:…"   9 days ago          Up 5 hours          0.0.0.0:9000->9000/tcp                             portainer
e0a5fd814dad        linuxserver/transmission            "/init"                  9 days ago          Up 5 hours          0.0.0.0:9091->9091/tcp, 0.0.0.0:51413->51413/tcp   transmission
166a7da8a1d4        linuxserver/sabnzbd                 "/init"                  6 weeks ago         Up 5 hours          9090/tcp, 0.0.0.0:32700->8080/tcp                  sabnzbd
701d0e5fd62e        linuxserver/sonarr                  "/init"                  6 weeks ago         Up 5 hours          0.0.0.0:8989->8989/tcp                             sonarr

2019-01-21 21:18:28.712 [   INFO] bouquet: Area 51/get.php - Music Choice | Pop & Country/Service01: mapped service from Area 51
2019-01-21 21:18:28.720 [   INFO] bouquet: Area 51/get.php - US | Viceland/Service01: mapped service from Area 51

tvh, is connected to the internet

Using iptv, input IPTV url, it connects and scans, EPG section of webui is blank, clients to the server are blank, client access is seen via webui to tvheadend server.

Using webui > configuration > EPG Grabber Modules > select external : XMLTV, save
The path shown is: /config/epggrab/xmltv.sock
docker is set to: ~/.docker/config/tvheadend/epggrab

ls -all :drwxrwxr-x  3 999 jerry    4096 Jan 21 12:38 .
drwxrwxr-x 17 999 jerry    4096 Jan 21 12:29 ..
-rw-rw-r--  1 999 jerry    8683 Dec  4 09:37 config
drwxrwxr-x  3 999 jerry    4096 Dec  4 09:35 xmltv
-rw-rw-r--  1 999 jerry     321 Jan 21 12:00 xmltv.log
-rw-rw-r--  1 999 jerry 1745769 Jan 21 12:00 xmltv.xml

locate xmltv.sock: /home/jerry/.docker/config/tvheadend/epggrab/xmltv.sock

ls -all /home/jerry/.docker/config/tvheadend/epggrab/xmltv.sock
ls: cannot access '/home/jerry/.docker/config/tvheadend/epggrab/xmltv.sock': No such file or directory

**Comment by halfagascan** [comment]
without this /config/epggrab/xmltv.sock, there is no way to socat the file

**Comment by olistudent** [comment]
Doesn't seem to be related to freetz? Is it?

**Comment by halfagascan** [comment]
What? what is freetz? no sense
