### ISSUE TITLE
/etc/hosts ipv6-addresses

### ISSUE THREAD

**Issue by WileC** [Freetz/freetz#74]
if you edit the hosts-file in the freetz-webif, then ipv6 adresses wouldn't be saved in /etc/hosts/. This could perhaps be due to the colons in the IP address, which is indeed "similar" as the MAC address looking.

**Comment by olistudent** [comment]
We have code in /usr/bin/modhosts for recognition of ip- and mac-addresses. Perhaps the ip part is outdated?
```
isip () {
  echo $1 | egrep '^[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}$' >/dev/null
}
ismac () {
  echo $1 | egrep '^[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}$' >/dev/null
}
```
