### ISSUE TITLE
[erledigt] Update DNSMasq to V2.80

### ISSUE THREAD

**Issue by WileC** [Freetz/freetz#78]

**Comment by fda77** [comment]
Witzig dass dir genau dnmasq einfällt. Hast kconfig vergessen ;-) Viel wichtiger sind aber daemons die nach aussen verbinden, wie privoxy, tor, lighttpd usw. busybox könnte auch mal ein update vertragen, ist 3 major versionen hintendran
Dann natürlich noch die ganzen libs

**Comment by WileC** [comment]
mit commit 14766f168239ad39c251da316e4201d144c50858 erledigt.
