### ISSUE TITLE
Kernel für 7270 kann nicht mehr gebaut werden

### ISSUE THREAD

**Issue by fda77** [Freetz/freetz#91]
Seit dem Hinzufügen von neuen Architekturen im letzten Jahr kann der Kernel für 7270 nicht mehr gebaut werden. Damit auch für alle Aliens wie die 7570

```
touch source/kernel/ref-ur8-7270_04.86/.modules-ur8
rm -f -r kernel/modules-ur8-7270_04.86/lib
mkdir -p kernel/modules-ur8-7270_04.86
tools/tar-gnu -cf - -C source/kernel/ref-ur8-7270_04.86/lib/modules/2.6.19.2-*-dirty/kernel --exclude=.svn --exclude=.gitignore --exclude=.build-prereq-checked --exclude=.unpacked --exclude=.configured --exclude=.compiled --exclude=.installed . | tools/tar-gnu -xf - -C kernel/modules-ur8-7270_04.86;
tools/tar-gnu: source/kernel/ref-ur8-7270_04.86/lib/modules/2.6.19.2-*-dirty/kernel: Cannot open: Datei oder Verzeichnis nicht gefunden
tools/tar-gnu: Error is not recoverable: exiting now
tools/tar-gnu: This does not look like a tar archive
tools/tar-gnu: Exiting with failure status due to previous errors
make/linux/kernel.mk:181: recipe for target 'kernel/modules-ur8-7270_04.86/.modules-ur8' failed
make: *** [kernel/modules-ur8-7270_04.86/.modules-ur8] Error 2

```
Ursache ist der fehlender Link source/kernel/ref-ur8-7270_04.86/lib/modules/2.6.19.2 auf das richtige Verzeichnis

**Comment by er13** [comment]
> Seit dem Hinzufügen von neuen Architekturen im letzten Jahr kann der Kernel für 7270 nicht mehr gebaut werden. 

Es hat rein gar nichts mit dem Hinzufügen von neuen Architekturen zu tun. Es hat nur damit zu tun, dass nach der svn=>git Migration nun innerhalb eines git checkouts übersetzt wird und das kernel build system beim Auffinden vom .git Verzeichnis bei gesetztem CONFIG_LOCALVERSION_AUTO eben irgendwelche Pfad-Suffixe erzeugt. Das Problem war schon immer da, die Migration hat dazu geführt, dass es endlich getriggert wurde.
